services:
  postgres:
    image: 'postgres:16'
    environment:
      - 'POSTGRES_DB=registrasidb'
      - 'POSTGRES_PASSWORD=registrasi123'
      - 'POSTGRES_USER=registrasi'
    ports:
      - '5432:5432'
    volumes:
      - ./db-registrasi:/var/lib/postgresql/data